// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU6YsFzluZKXa7VuJkGYO3ovORZ4NtKSQ',
    appId: '1:681987159038:web:9a1b6087a47603af9986af',
    messagingSenderId: '681987159038',
    projectId: 'petcare-c6a5f',
    authDomain: 'petcare-c6a5f.firebaseapp.com',
    storageBucket: 'petcare-c6a5f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTTjqFnkPqlIB8ONPaO74BX8QR2mGjL0Y',
    appId: '1:681987159038:android:2a5529ecbdd3d0389986af',
    messagingSenderId: '681987159038',
    projectId: 'petcare-c6a5f',
    storageBucket: 'petcare-c6a5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA78m5p4QUx3IHzu26ATA8YV9q4P6GVrOw',
    appId: '1:681987159038:ios:945a33d20b5fe93c9986af',
    messagingSenderId: '681987159038',
    projectId: 'petcare-c6a5f',
    storageBucket: 'petcare-c6a5f.appspot.com',
    iosClientId: '681987159038-k10lkjeg9m3u8nf73fa36oe035565h5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.petcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA78m5p4QUx3IHzu26ATA8YV9q4P6GVrOw',
    appId: '1:681987159038:ios:945a33d20b5fe93c9986af',
    messagingSenderId: '681987159038',
    projectId: 'petcare-c6a5f',
    storageBucket: 'petcare-c6a5f.appspot.com',
    iosClientId: '681987159038-k10lkjeg9m3u8nf73fa36oe035565h5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.petcare',
  );
}
